In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model, metrics

In [2]:
df = pd.read_csv('heart.csv')
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


## Checking outlier with Z-score

In [4]:
import scipy.stats as stats

In [5]:
df[(np.abs(stats.zscore(df["Age"])) >= 10)]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [6]:
df[(np.abs(stats.zscore(df["RestingBP"])) >= 10)]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [7]:
df[(np.abs(stats.zscore(df["Cholesterol"])) >= 10)]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [8]:
df[(np.abs(stats.zscore(df["FastingBS"])) >= 10)]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [9]:
df[(np.abs(stats.zscore(df["MaxHR"])) >= 10)]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [10]:
df[(np.abs(stats.zscore(df["Oldpeak"])) >= 10)]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

## mengubah tipe data objek ke dalam data numerik

In [11]:
df.replace(['M', 'F'], [0, 1], inplace=True) #Sex
df.replace(['TA', 'ATA', 'NAP', 'ASY'], [0, 1, 2, 3], inplace=True) #ChestPainType
df.replace(['Normal', 'ST', 'LVH'], [0, 1, 2], inplace=True) #RestingECG
df.replace(['N', 'Y'], [0, 1], inplace=True) #ExerciseAngina
df.replace(['Up', 'Flat', 'Down'], [0, 1, 2], inplace=True) #ST_Slope
df

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    0              1        140          289          0           0   
1     49    1              2        160          180          0           0   
2     37    0              1        130          283          0           1   
3     48    1              3        138          214          0           0   
4     54    0              2        150          195          0           0   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    0              0        110          264          0           0   
914   68    0              3        144          193          1           0   
915   57    0              3        130          131          0           0   
916   57    1              1        130          236          0           2   
917   38    0              2        138          175          0           0   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0      172               0      0.0         0             0  
1      156               0      1.0         1             1  
2       98               0      0.0         0             0  
3      108               1      1.5         1             1  
4      122               0      0.0         0             0  
..     ...             ...      ...       ...           ...  
913    132               0      1.2         1             1  
914    141               0      3.4         1             1  
915    115               1      1.2         1             1  
916    174               0      0.0         1             1  
917    173               0      0.0         0             0  

[918 rows x 12 columns]

In [12]:
df.to_csv("HeartDiseasePredict.csv", index = False)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    int64  
 2   ChestPainType   918 non-null    int64  
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    int64  
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    int64  
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    int64  
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(11)
memory usage: 86.2 KB


## pengelompokan atribut X dan y

In [14]:
X = df.loc[:, df.columns != 'HeartDisease']
y = df["HeartDisease"]

In [15]:
X.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    0              1        140          289          0           0   
1   49    1              2        160          180          0           0   
2   37    0              1        130          283          0           1   
3   48    1              3        138          214          0           0   
4   54    0              2        150          195          0           0   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
0    172               0      0.0         0  
1    156               0      1.0         1  
2     98               0      0.0         0  
3    108               1      1.5         1  
4    122               0      0.0         0

In [16]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

## train test split

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)

## logistic regression

In [18]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr = lr.fit(X_train, y_train)
lr

C:\Users\Ali Prasetya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

## decision tree

In [19]:
from sklearn import tree

dtree = tree.DecisionTreeClassifier()
dtree = dtree.fit(X_train, y_train)

## random forest classifier

In [20]:
from sklearn.ensemble import RandomForestClassifier

classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5,
                                       n_estimators=60, oob_score=True)

classifier_rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, n_estimators=60, n_jobs=-1, oob_score=True,
                       random_state=42)

## hyperparameter tuning

In [21]:
rf = RandomForestClassifier(random_state=60, n_jobs=-1)

params = {
    'max_depth': [2,3,5,10,20],
    'min_samples_leaf': [5,10,20,50,100,200],
    'n_estimators': [10,25,30,50,100,200]
}

In [22]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator=rf,
                           param_grid=params,
                           cv = 5,
                           n_jobs=-1, verbose=1, scoring="accuracy")

grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 180 candidates, totalling 900 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(n_jobs=-1, random_state=60),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100, 200],
                         'n_estimators': [10, 25, 30, 50, 100, 200]},
             scoring='accuracy', verbose=1)

In [23]:
grid_search.best_score_

0.8727272727272727

In [24]:
rf_best = grid_search.best_estimator_
rf_best.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=5, n_estimators=200,
                       n_jobs=-1, random_state=60)

In [25]:
y_pred = classifier_rf.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
score

0.8777173913043478

## menyimpan model ke dalam bentuk .pkl

In [27]:
import joblib

joblib.dump(lr, 'model_logisticregression.pkl')
joblib.dump(classifier_rf, 'model_classifier_rf.pkl')
joblib.dump(rf_best, 'model_classifier_rf_hypertuned.pkl')

['model_classifier_rf_hypertuned.pkl']

## evaluasi

In [28]:
y_lr = lr.predict(X_test)
y_dtree = dtree.predict(X_test)
y_rf = rf_best.predict(X_test)

### confussion matrix

In [35]:
from sklearn.metrics import confusion_matrix
print("Logistic Regression : \n", confusion_matrix(y_test, y_lr))
print("Random Forest awal : \n", confusion_matrix(y_test, y_dtree))
print("Random Forest setelah Hyperparameter tuning : \n", confusion_matrix(y_test, y_rf))

Logistic Regression : 
 [[134  19]
 [ 35 180]]
Random Forest awal : 
 [[127  26]
 [ 63 152]]
Random Forest setelah Hyperparameter tuning : 
 [[130  23]
 [ 27 188]]


### classification report

In [37]:
from sklearn.metrics import classification_report
print("Logistic Regression : \n\n", classification_report(y_test, y_lr))
print("Random Forest awal : \n\n", classification_report(y_test, y_dtree))
print("Random Forest setelah Hyperparameter tuning : \n\n", classification_report(y_test, y_rf))

Logistic Regression : 

               precision    recall  f1-score   support

           0       0.79      0.88      0.83       153
           1       0.90      0.84      0.87       215

    accuracy                           0.85       368
   macro avg       0.85      0.86      0.85       368
weighted avg       0.86      0.85      0.85       368

Random Forest awal : 

               precision    recall  f1-score   support

           0       0.67      0.83      0.74       153
           1       0.85      0.71      0.77       215

    accuracy                           0.76       368
   macro avg       0.76      0.77      0.76       368
weighted avg       0.78      0.76      0.76       368

Random Forest setelah Hyperparameter tuning : 

               precision    recall  f1-score   support

           0       0.83      0.85      0.84       153
           1       0.89      0.87      0.88       215

    accuracy                           0.86       368
   macro avg       0.86      0

### AUC

In [33]:
from sklearn.metrics import roc_curve, auc
fpr, tpr, thresholds = roc_curve(y_test, y_lr, pos_label=1) # pos_label: positive label
print("Logistic Regression : ", auc(fpr, tpr))
fpr, tpr, thresholds = roc_curve(y_test, y_dtree, pos_label=1) # pos_label: positive label
print("Random Forest awal : ", auc(fpr, tpr))
fpr, tpr, thresholds = roc_curve(y_test, y_rf, pos_label=1) # pos_label: positive label
print("Random Forest setelah Hyperparameter tuning : ", auc(fpr, tpr))

Logistic Regression :  0.8565131478948169
Random Forest awal :  0.7685210518315853
Random Forest setelah Hyperparameter tuning :  0.862045903632771


## Conclusion

Setelah dilakukan evaluasi dengan ketiga metode diatas, dapat disimpulkan bahwa model terbauk yang digunakan adalah Random Forest setelah Hyperparameter Tuning. 

Hal ini dikarenakan nilai atau skor pada Hyperparameter Tuning pada masing-masing metode evaluasi memiliki nilai yang lebih tinggi daripada metode confussion matrix dan meetode AUC 